wordle:
  schedule: "0 7 * * *"   # 7:00 AM ET
  validator: "^[a-z]{5}$"
  sources:
    - name: toms_guide
      type: regex_list
      url: https://www.tomsguide.com/news/what-is-todays-wordle-answer
      patterns:
        - "Today's Wordle answer[^\\n]*?is\\s+([A-Za-z]{5})\\b"
        - "The solution[^\\n]*?is\\s+([A-Za-z]{5})\\b"
      weight: 1.4
    - name: techradar
      type: regex_list
      url: https://www.techradar.com/news/wordle-today
      patterns:
        - "Wordle answer[^\\n]*?is\\s+([A-Za-z]{5})\\b"
      weight: 1.3
    - name: nme
      type: regex_list
      url: https://www.nme.com/guides/gaming-guides/heres-the-wordle-answer-for-today-3171240
      patterns:
        - "Wordle answer[^\\n]*?is\\s+([A-Za-z]{5})\\b"
      weight: 1.2
  template: "wordle.html.j2"
  output_prefix: "wordle"
